package com.myproject.spacegame.buildingStats;

public enum NamesOfPlanetBuildings {

	METALMINE, CRYSTALMINE, HYDROGENPLANT, SOLARPOWERPLANT, METALSTOREHOUSE, CRYSTALSTOREHOUSE, HYDROGENTANK, COMMANDCENTRAL, SOLARSATELLITE;
}
