package com.myproject.spacegame.user.planet.buildings;

public enum NamesOfPlanetBuildings {

	METALMINE, CRYSTALMINE, HYDROGENPLANT, SOLARPOWERPLANT, METALSTOREHOUSE, CRYSTALSTOREHOUSE, HYDROGENTANK, COMMANDCENTRAL;
}
